create table schema_migrations
(
    version bigint  not null
        primary key,
    dirty   boolean not null
);

alter table schema_migrations
    owner to admin;

create table users
(
    id            integer generated by default as identity
        primary key,
    nickname      varchar(50)  not null
        unique,
    email         varchar(255) not null
        unique,
    password_hash text         not null,
    created_at    timestamp default now(),
    updated_at    timestamp default now()
);

alter table users
    owner to admin;

create table refresh_tokens
(
    id         integer generated by default as identity
        primary key,
    user_id    integer
        references users
            on delete cascade,
    token      text      not null,
    expires_at timestamp not null,
    created_at timestamp default now()
);

alter table refresh_tokens
    owner to admin;

create table chats
(
    id         integer generated by default as identity
        primary key,
    name       varchar(255)            not null,
    type       varchar(20)             not null,
    created_at timestamp default now() not null
);

alter table chats
    owner to admin;

create table chat_participants
(
    chat_id   integer                 not null
        references chats
            on delete cascade,
    user_id   integer                 not null,
    role      varchar(20)             not null,
    joined_at timestamp default now() not null,
    primary key (chat_id, user_id)
);

alter table chat_participants
    owner to admin;

create table messages
(
    id         integer generated by default as identity
        primary key,
    chat_id    integer                 not null
        references chats
            on delete cascade,
    sender_id  integer                 not null,
    content    text                    not null,
    created_at timestamp default now() not null
);

alter table messages
    owner to admin;

